// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/dashboard";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/dashboard")>;
      $$route?: undefined;
    },
    {
      path: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
    },
    {
      path: "/login";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/login")>;
      $$route?: undefined;
    },
    {
      path: "/register";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/register")>;
      $$route?: undefined;
    },
    {
      path: "/write";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/write")>;
      $$route?: undefined;
    },
    {
      path: "/edit/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/edit/[id]")>;
      $$route?: undefined;
    },
    {
      path: "/post/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/post/[id]")>;
      $$route?: undefined;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/";
      id: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/login";
      id: "/login";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/login")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/write";
      id: "/write";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/write")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/register";
      id: "/register";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/register")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/edit/:id";
      id: "/edit/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/edit/[id]")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/post/:id";
      id: "/post/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/post/[id]")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/dashboard";
      id: "/dashboard";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/dashboard")>;
      $$route?: undefined;
      children?: undefined;
    }
  ];
}
